/*MI VADO A CREARE IL DATA BASE PER LA PALESTRA */
CREATE DATABASE 'PALESTRA';
USE 'PALESTRA';

CREATE TABLE CLIENTE(
    cod_F VARCHAR(16) NOT NULL PRIMARY KEY,/*METTO SEDICI PERCHE è IL CODICE FISCLE*/
    email VARCHAR(65) NOT NULL,
    name_user VARCHAR(10) NOT NULL,
    pwd VARCHAR(40) NOT NULL,
    nome VARCHAR(30) NOT NULL,
    cognome VARCHAR(30) NOT NULL,
    nascita DATE NOT NULL,
    telefono VARCHAR(11)NOT NULL,
    altezza INT(3)  UNSIGNED  NOT NULL,
    peso decimal(5,2) UNSIGNED NOT NULL,
    attivo bit NOT NULL DEFAULT TRUE
);
CREATE TABLE CERTIFICATO_MEDICO(
    PUC VARCHAR(9) NOT NULL PRIMARY KEY, /*PUC PROTOCOLLO UNIVOCO DEL CERTIFICATO MEDICO COMPOSTO DA NOVE CIFRE*/
    url_foto VARCHAR(150) NOT NULL,/*un url per una imagina puo avere fino a 300 caratteri*/
    data_certificato DATE NOT NULL,
    approvato bit not null,
    fk_cliente VARCHAR(16) NOT NULL,
    CONSTRAINT fk_certificato_cliente /* NOME DEL VINCOLO */
    FOREIGN KEY fk_cliente REFERENCES CLIENTE(cod_F)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);
CREATE TABLE ACCESSO(
    id_accesso int(6) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT PRIMARY KEY,
    data_accesso TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, /* TIMESTAMP salva data e ora dell'istante in cui viene inserito */
    fk_cliente VARCHAR(16) NOT NULL,
    CONSTRAINT fk_accesso_cliente /* NOME DEL VINCOLO */
    FOREIGN KEY fk_cliente REFERENCES CLIENTE(cod_F)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);
CREATE TABLE ABBONAMENTO(
    id_abb int(3) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT PRIMARY KEY,
    inzio DATE NOT NULL,
    fk_cliente VARCHAR(16) NOT NULL,
    fk_tipo int(1)NOT NULL
    CONSTRAINT fk_abbonamento_cliente /* NOME DEL VINCOLO */
    FOREIGN KEY fk_cliente REFERENCES CLIENTE(cod_F)
        ON DELETE CASCADE
        ON UPDATE CASCADE
    
    CONSTRAINT fk_abbonamento_tipo /* NOME DEL VINCOLO */
    FOREIGN KEY fk_tipo REFERENCES TIPO(id_tipo)
        ON DELETE CASCADE
        ON UPDATE CASCADE
   
);
CREATE TABLE TIPO(
    id_tipo int(1) NOT NULL PRIMARY KEY,/*NON PREVEDOTO PIU DI NOVE TIPI DI ABBONAMENTO*/ 
    prezzo float(6,2) NOT NULL, 
    durata date NOT NULL
);
CREATE TABLE SERVIZIO(
     id_servizio INT(1) NOT NULL PRIMARY KEY,/*non prevedo piu di nove servizi=SPORT */
     nome VARCHAR(20) NOT NULL ,
     int tipo NOT NULL 

);
CREATE TABLE PRENOTAZIONE {
    n_prenotazion INT(2) NUll PRIMARY KEY,
    quando DATE NOT NULL 
};
CREATE TABLE CORSO(
    id_corso INT(2) NOT NULL PRIMARY KEY,
    nome VARCHAR(15) NOT NULL ,
    livello INT(1) NOT NULL
/*NON PREVEDO PIU DI NOVE LIVELI */
);
CREATE TABLE SCHEDA(
    n_scheda INT(3)NOT NULL UNSIGNED PRIMARY KEY,
    cognome VARCHAR (20) NOT NULL,
    NOME VARCHAR (20) NOT NULL,
    data_inzio DATE NOT NULL,
    durata INT(2) NOT NULL,/*OBLIGATO A METTERE DUE PERCHE IN UN HANNO CI SONO 12 MESI COMPOSTO DA DUE CIFRE*/
    obbiettivo VARCHAR(40)NOT NULL /*HO MESSO 40 CARATTERI PERCHE LO PNSATA IN MODO CHE POSSANO SCRIVERE UNA MINI FRASE TIPO OBBIETTIVO:RICOMPOSIZIONE CORPOREA E AUMENTO DELLA MASSA MAGRA */N

);
CREATE TABLE PRESONALE(
    cod_F VARCHAR(16) NOT NULL PRIMARY KEY,/*METTO SEDICI PERCHE è IL CODICE FISCLE*/
    nome VARCHAR(30) NOT NULL,
    cognome VARCHAR(30) NOT NULL,
    numero_T VARCHAR(15) NOT NULL 

);
CREATE TABLE ESTERNO(
    id_eseterno INT(1) NOT NULL PRIMARY KEY,
    numero_t_aziendale VARCHAR(15) NOT NULL,

);
CREATE TABLE PT(/*PT=tabella personala trainer*/
    corso_studio VARCHAR(30) NOT NULL PRIMARY KEY,
    livello INT(1) NOT NULL /*NON PENSAVO PIU DI 3 PRINCIPIANTE INTERMEDIO ESPERTO*/
);
CREATE TABLE ATTREZZO (
    id_atttrezzzo VARCHAR(10) NOT NULL PRIMARY KEY,
    tipo varchar(20) NOT NULL,
    NOME VARCHAR(30) NOT NULL,
    peso_max int (3) NOT NULL,
    peso_min int (3) NOT NULL 
);
CREATE TABLE ESRCIZIO(
 id_es VARCHAR(10) NOT NULL PRIMARY KEY,
 NOME VARCHAR(20) NOT NULL 
);
    